
name: phaser_flutter_game
description: A Flutter app that runs a Phaser web game.
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  flutter_inappwebview: ^6.0.0
  path_provider: ^2.1.1
  
flutter:
  uses-material-design: true
  assets:
    - public/
    - public/assets/
